
[theme]
primaryColor="#B892FF"                # Soft violet (buttons, accents)
backgroundColor="#0D0D0D"             # Deep black (main background)
secondaryBackgroundColor="#1C1C1E"    # Slightly lighter (sidebar/widgets)
textColor="#E0E0E0"                   # Light gray (easy on eyes)
font="sans serif"                     # Clean and modern
